export const customerCommitmentSeeds = [
  {
    type: 'air_freight_direct',
    warehouse_required: false,
    storage_required: false,
    delivery_required: true,
    freight_type: 'air',
    export_required: true,
    notes: 'Air Freight Direct to Customer - fastest option, highest freight cost',
  },
  {
    type: 'port_delivery',
    warehouse_required: false,
    storage_required: false,
    delivery_required: true,
    freight_type: 'ocean',
    export_required: true,
    notes: 'Delivery to Port for Customer Shipment - Incoterms apply',
  },
  {
    type: 'warehouse_pickup',
    warehouse_required: true,
    storage_required: true,
    delivery_required: false,
    freight_type: null,
    export_required: false,
    notes: 'Delivery to Our Warehouse, Customer Pickup - receiving and storage fees apply',
  },
  {
    type: 'warehouse_to_dc',
    warehouse_required: true,
    storage_required: true,
    delivery_required: true,
    freight_type: 'local',
    export_required: false,
    notes: 'Delivery to Our Warehouse, Then Deliver to Customer Warehouse / DC',
  },
  {
    type: 'custom_path',
    warehouse_required: false,
    storage_required: false,
    delivery_required: false,
    freight_type: null,
    export_required: false,
    notes: 'Custom Path - manual estimate required, always flags for approval',
  },
];
